### ISSUE TITLE
Issues with contact selection dialog

### ISSUE THREAD

**Issue by tuokiv** [aebruno/whisperfish#100]
New contact selection dialog is better than old version, but it's not showing contacts starting with scandinavian letters (for example "äiti" = mom in finnish) and special characters (for example <3). Also not informing anymore whether recipient is Signal user or not (maybe it's possible in futute version show only Signal contacts)? Some contats appear dublicate, maybe those who are using Signal.

**Comment by d9h20f** [comment]
Another huge problem: it doesn't scroll, so you can only see a couple of contacts.

**Comment by TimorLee** [comment]
I also have the same problem as @d9h20f ...

**Comment by aebruno** [comment]
Yes, the contact selection still needs some work still. Unfortunately, sailfish silica does not include a "ContactPicker". Would be great if this was part of the new pickers. I'm currently using a standalone contact picker available [here](https://github.com/r0kk3rz/sailfish-alphabet-sort) and having some trouble getting the scrolling working correctly. Any QML gurus out there would love some help on this one. If someone can get scrolling to work in sailfish-alphabet-sort, it's easy to port into whisperfish.

**Comment by sfbg** [comment]
It is perhaps important to note that, currently, even the visible entries are either sorted inconsistently or entries are missing, hard to tell without being able to scroll to the bottom of the list.

**Comment by r0kk3rz** [comment]
You don't have scrolling? I have scrolling in my SirenSong app that i built the sailfish-alphabet-sort component for.

So long as the whole thing is wrapped in a flickable it should scroll just fine

**Comment by aebruno** [comment]
@r0kk3rz Thanks for the reply and thanks for the awesome alphabet-sort component. I'm using it in a Dialog so that must be why scrolling isn't working. eg. https://github.com/aebruno/whisperfish/blob/master/qml/pages/SelectContact.qml

I'll try to refactor it to use a flickable. Thanks again!

**Comment by aebruno** [comment]
@r0kk3rz Wrapping in a flickable worked great. Thanks again for the tip and the awesome component!

**Comment by sfbg** [comment]
Can confirm that scrolling works fine in 0.5.1

**Comment by r0kk3rz** [comment]
as for the original issue, yes the alphabet in this component is hardcoded and so its not very friendly to languages without english characters, which will make it unusuable for people with russian language.

It should be fixable but I was just learning qml at the time I made this
