### ISSUE TITLE
Message list titles not updated until new message or restart

### ISSUE THREAD

**Issue by tuokiv** [aebruno/whisperfish#106]
Titles (today, yesterday, earlier) at message list are not updated without some activity, for example new message or restarting Whisperfish.

**Comment by tuokiv** [comment]
Actually sendin new messagw doesn't solve this problem, it updated only current conversation under correct timestamp title. Only restarting updates list correctly.

**Comment by d9h20f** [comment]
Jolla's Messages application actually suffers from the same problem.

**Comment by aebruno** [comment]
No need to restart.. you can go to `Settings -> Refresh Contacts` and it will update the message list.

**Comment by tuokiv** [comment]
Shouldn't it still happen automatically at midnight?

**Comment by aebruno** [comment]
Yes, it should and will add it to the todo list. But in the mean time you can use the `Settings -> Refresh Contacts` to update the list.
