### ISSUE TITLE
Pictures Attachment

### ISSUE THREAD

**Issue by monkeyisland1992** [aebruno/whisperfish#107]
No list or prewiev for pictures.
Documents or Videos,Music is working.

**Comment by monkeyisland1992** [comment]
solved sorry i did a reboot, and started whisperfish again.

**Comment by Nokius** [comment]
I have a similar issue. during the day I saw less and less previews of my pictures. First time I saw all then I saw a few (like one or two per line) then nothing. It been separated attachments in the same chat. Could it be an issue with Tracker?
