### ISSUE TITLE
lost all contact names

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#11]
hi,

at some point in the iteration process contact names got all lost. Only numbers are present at all. Is already a log output available? Start the app with specific parameters to get those logs? I think its hard to determine else. Contacts refresh isn't helping. Maybe it's important to know that all my contacts are synced via jolla carddav account.

**Comment by carepack** [comment]
and have you seen my comment on this:
https://github.com/aebruno/whisperfish/issues/9

**Comment by aebruno** [comment]
> at some point in the iteration process contact names got all lost. Only numbers are present at all.

You can check the local contact database:

    $ sqlite3 /home/nemo/.local/share/system/Contacts/qtcontacts-sqlite/contacts.db
    sqlite> select phoneNumber from PhoneNumbers;

These are the numbers whisperfish will try to parse using the Country Code you set in the settings page. 

> Is already a log output available? Start the app with specific parameters to get those logs?

Logging should be enabled by default and you should see error messages in the console. I will add some more Info logs to the contact parsing to help debug.

**Comment by aebruno** [comment]
> at some point in the iteration process contact names got all lost.

Things are under heavy development at the moment, thanks for your patience! Once I finish up a few more features I'll settle things down and start on a release cycle.

**Comment by carepack** [comment]
np bruno. you're working that fast already! thx for you're efforts. I'll check you're suggestion.

**Comment by carepack** [comment]
ah. for information. you're suggestion brought me to the simple idea to reconfigure the country code and let it sync again. the names present now. So, after upgrading the app it could be possible that the country code have to be updated.
