### ISSUE TITLE
Resending message with wrong unsent status crashes the app

### ISSUE THREAD

**Issue by sfbg** [aebruno/whisperfish#111]
Sometimes, not too often, an outgoing message that was actually successfully sent and received by the other chat participant is erroneously shown to be unsent (x sign). The messages that are sent after it do not have the same problem and show the correct (two checkmarks) status.

Trying to resend the message always crashes Whisperfish.

If I do not try to resend it, but just restart the app myself, the status of the problematic message is correct (two checkmarks) after the restart.

This is not a new 0.5 issue, I just came to report it now. It was there at least in the 0.4 releases for sure too.

**Comment by aebruno** [comment]
@sfbg Thanks for the report. If you could grab some logs of the crash that would be helpful.

**Comment by sfbg** [comment]
Sorry, where should I look for the logs? Should I start Whisperfish with some special parameters?

**Comment by aebruno** [comment]
> Sorry, where should I look for the logs? Should I start Whisperfish with some special parameters?

See this comment https://github.com/aebruno/whisperfish/issues/78#issuecomment-293264856

**Comment by sfbg** [comment]
Managed to replicate it at last with debugging on. Here are the last lines of the file under /tmp:

```
time="2018/07/25 10:17:13" level=debug msg="Websocket sending message"
time="2018/07/25 10:17:47" level=debug msg="Sending websocket ping message"
time="2018/07/25 10:17:48" level=debug msg="Received websocket pong message"
time="2018/07/25 10:18:41" level=debug msg="Sending websocket ping message"
time="2018/07/25 10:18:42" level=debug msg="Received websocket pong message"
time="2018/07/25 10:19:55" level=debug msg="Sending websocket ping message"
time="2018/07/25 10:19:55" level=debug msg="Received websocket pong message"
time="2018/07/25 10:19:57" level=debug msg="Message received handler"
time="2018/07/25 10:19:57" level=info msg="Message received" isSyncSent=false source=+XX ts=0
time="2018/07/25 10:19:57" level=debug msg="Websocket sending message"
time="2018/07/25 10:20:22" level=debug msg="Message received handler"
time="2018/07/25 10:20:22" level=info msg="Message received" isSyncSent=false source=+XX ts=0
time="2018/07/25 10:20:22" level=debug msg="Websocket sending message"
time="2018/07/25 10:20:49" level=debug msg="Sending websocket ping message"
time="2018/07/25 10:20:52" level=debug msg="Received websocket pong message"
time="2018/07/25 10:20:53" level=debug msg="PUT /v1/messages/+YY 200\n"
time="2018/07/25 10:20:53" level=debug msg="SendMessageResponse: {NeedsSync:false Timestamp:1532506838899}\n"
time="2018/07/25 10:20:53" level=debug msg="PUT /v1/messages/+XX 200\n"
time="2018/07/25 10:20:53" level=debug msg="SendMessageResponse: {NeedsSync:false Timestamp:1532506853146}\n"
time="2018/07/25 10:20:53" level=debug msg="Message receipt handler"
time="2018/07/25 10:20:53" level=debug msg="Receipt handler" devID=1 source=+YY timestamp=1532506853146
time="2018/07/25 10:20:54" level=debug msg="Websocket sending message"
time="2018/07/25 10:20:54" level=debug msg="Message receipt handler"
time="2018/07/25 10:20:54" level=debug msg="Receipt handler" devID=1 source=+XX timestamp=1532506838899
time="2018/07/25 10:20:54" level=error msg="Failed to fetch message from queue" error="sql: no rows in result set" id=12610
```

In the console there was some other output that just before the crash (retyped per hand):
```
[D]  :113 - Resending message: 12610
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x8 pc=0x432cb8J62ff7588308d9199ff
```

**Comment by aebruno** [comment]
> In the console there was some other output that just before the crash (retyped per hand):

Thanks for the log. The other out output from the console would be helpful to have. Is there any more info you can provide from those messages?

**Comment by sfbg** [comment]
I do not have it anymore as the console output was mixed up somehow... From what I could see there were no untypical lines before the ones above.

The error appeared within a group chat with two other participants, but this is not always the case sometimes it happens in simple chats too...

**Comment by sfbg** [comment]
I do not know it this is relevant, but it might be. Just checked, in the settings screen it says "Total  messages: 12380". The id in the log is 12610...
