### ISSUE TITLE
Secure storage using sailfish-secrets

### ISSUE THREAD

**Issue by rubdos** [aebruno/whisperfish#117]
Hi! Have you explored https://github.com/sailfishos/sailfish-secrets yet? It was just announced on https://together.jolla.com/question/184471/release-notes-220-mouhijoki/ afaict.

It seems like a secure storage API, which might be worthwhile to use instead of the passphrase for storing the private key material.

**Comment by aebruno** [comment]
Yes, I've been following. Will definitely be checking it out and seeing how best to incorporate it into whisperfish.
