### ISSUE TITLE
start Whisperfish with stored password

### ISSUE THREAD

**Issue by xjcoder** [aebruno/whisperfish#118]
Hi there, I use Whisperfish on my AquaFish/Jolla C, but I don't want to type the password each time the app starts.
I know there is a config-file (config.yml) with the property ' storagePassword: "" ' - is it possible to store the password there? I think the password has to be encrypted, right? How can I do this? 
The only way that i found, was to decrypt the whole whisperfish/signal-database and store the clear password into the property.
Any other suggestions?

**Comment by aebruno** [comment]
This is currently not supported but will try and add support in future releases. One option might be to use sailfish-secrets so whisperfish would use your device password. You can follow that issue #117
