### ISSUE TITLE
[issue] send attachments not visibile for contacts 

### ISSUE THREAD

**Issue by Nokius** [aebruno/whisperfish#119]
since the last days I get complaints that my attached files are broken if I send them to iOS users.
I'm not sure if this happend after the  updating to 2.2.0.29 or this has no relation.

It is reproducible with different Contacts.

**Comment by bonanza123** [comment]
I also got complains from Android users that they cannot send photos anymore to me. But sofar, I didn't check that further...

**Comment by Nokius** [comment]
@bonanza123 I will check if I can receive attachments

**Comment by Nokius** [comment]
I was able to send / receive Picture attachments to iOS But I see in the chat logs that it failed during the week. Maybe something was shaky on the signal infra :-/

**Comment by bonanza123** [comment]
@Nokius thanks for trying!
I also tried it today again with Android. The photos from android are received by Signal desktop only, but they don't appear in whisperfish.

**Comment by Nokius** [comment]
I had issues for this files (shared from whisperfish) with the desktop too
I didn't received files so I only can say I shared 

just got a confirmation from another contact that it worked it's working again 

@bonanza123 did you restarted wisperfish?

**Comment by bonanza123** [comment]
@Nokius I just restarted whisperfish to see whether photo from this morning could be received with some delay. But it still doesn't show up...

**Comment by Nokius** [comment]
:-/ I was never able to receive old attachments. Like after joining a better network. I bet this will not work
