### ISSUE TITLE
[Q] Provide a qt go bundle used for build

### ISSUE THREAD

**Issue by oleid** [aebruno/whisperfish#120]
I've trouble compiling the Qt go bindings on my system. Could you maybe provide a zip file ready for unpacking to sb2?

**Comment by aebruno** [comment]
Did the "Building from source" docs not work for you? What errors did you hit? Would love to hear any feedback on the build process.

**Comment by oleid** [comment]
First of all, it would seem I had to manually install go-Qt's deps for the bootstrap to succeed.

<pre>
go get -u github.com/sirupsen/Logrus
go get -u golang.org/x/crypto/ssh
</pre>

Possibly do to logrus's rename, I'm not sure.

Then, Qt4.7 isn't available for download anymore. Having Qt development packages installed anyway, I tried to use my system's Qt. That would be 5.11.1. But I couldn't convince qtmoc during the `prep` phase to use the correct paths. But I just realized, that a special android version was used, so using my system Qt seems pointless now. Qt's archive server has still the run file,  I'll try and report back.

**Comment by oleid** [comment]
Okay, I think it would make sense to mention, that the build scripts assume, that you install the official binary distribution and set a `GOROOT`. Using go on linux, usually setting `GOROOT` is not needed when using your distro's packages. Also, you've to install the official binaries of go to `$HOME/projects/goroot`, otherwise the `compile` step fails.
