### ISSUE TITLE
Phone number prompt locked

### ISSUE THREAD

**Issue by ninewise** [aebruno/whisperfish#126]
When I try to run whisperfish (release 0.5.1) on my Gemini PDA, I'm prompted to insert my phone number (I'm assuming this it's my phone number being asked because I get [this placeholder](https://github.com/aebruno/whisperfish/blob/master/qml/pages/Register.qml#L45)). I can't change the value in the textfield or do anything else on the page, though, except hitting "Cancel" and enabling/disabling the "Share Contacts" checkmark.

I've already tried to register outside the app succesfully, getting the 6-digit code as described [here](https://together.jolla.com/question/181042/whisperfish-device-verification-code/?answer=183826#post-id-183826), but I can't find anywhere to insert it into whisperfish.

**Comment by marxistvegan** [comment]
> When I try to run whisperfish (release 0.5.1) on my Gemini PDA, I'm prompted to insert my phone number (I'm assuming this it's my phone number being asked because I get [this placeholder](https://github.com/aebruno/whisperfish/blob/master/qml/pages/Register.qml#L45)). I can't change the value in the textfield or do anything else on the page, though, except hitting "Cancel" and enabling/disabling the "Share Contacts" checkmark.

It is your number being asked and that can easily be to a number that can be called as that is how it will give you the verification code. 
I know when I have used whisperfish I for some reason forget to type my number in, @aebruno maybe making the placeholder grey would help.

**Comment by ninewise** [comment]
I think there's some confusion. I know it's the telephone number. I can't change the textfield into anything instead of the placeholder. It's not editable.
