### ISSUE TITLE
Could Whisperfish be built on Windows/Mac (to provide a native Signal desktop app)?

### ISSUE THREAD

**Issue by tkafka** [aebruno/whisperfish#128]
Hello, just an uninformed question - would it be possible (easy? hard?) to turn Whisperfish into a native desktop Signal app, as it's built on Go and QT?

**Comment by jtl999** [comment]
Linux too :)

It sounds like a good idea and I would LOVE for a "native" Signal desktop client to happen, but seeing how this is [EOL and unmaintained](https://github.com/aebruno/whisperfish/issues/130), probably don't base it on this
