### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#13]
hi,

package import of:

https://github.com/aebruno/whisperfish/commit/3c343eda93cefddef9e7f906e2ec59eed0e6c749#diff-1a60e1c4cc0c82b6f9d8eef9bcb80257R21

fails. Maybe line 26 is causing the problem? Can't build a new package.

`go build
gopkg.in/qml.v1/whisperfish
./devices.go:26: undefined: "github.com/janimo/textsecure".DeviceInfo
`

after playing around a little bit with the url I got follwing output:

`# gopkg.in/qml.v1/whisperfish
./devices.go:21: non-canonical import path "github.com/janimo/textsecure/" (should be "github.com/janimo/textsecure")
./devices.go:21: can't find import: "github.com/janimo/textsecure/"
`

thx for youre work bruno

**Comment by aebruno** [comment]
The most recent commit 3c343eda93cefddef9e7f906e2ec59eed0e6c749 adds support for device linking with Signal-Desktop. This depends on an outstanding pull request that is currently under review janimo/textsecure#28. In the mean time you can use this branch https://github.com/aebruno/textsecure/tree/device-provisioning for building.

**Comment by carepack** [comment]
Yeah,

I saw that it's related to the desktop app link. . NP. In that case I'll wait until the commit is accepted. Thx for the fast reply .

**Comment by carepack** [comment]
I can't build it. 

`/src/github/aebruno/texsecure  branch device-provisioning
/src/gopkg/qmlv1 branch whisperfish
/src/gopkg/qmlv1/whisperfish branch master`

running go build results in

`# gopkg.in/qml.v1/whisperfish
./devices.go:26: undefined: "github.com/janimo/textsecure".DeviceInfo`

**Comment by aebruno** [comment]
You need to replaced the package similar to how you did the qml.v1 package. So try this:

    $ cd ~/src/github.com/janimo
    $ rm -Rf textsecure
    $ git clone https://github.com/aebruno/textsecure.git
    $ cd textsecure
    $ git checkout device-provisioning
    $ go install .

Then you should be all set.

**Comment by carepack** [comment]
thx bruno. yeah, build worked. But the build can't open message store. No Messages after unlocking with pw

**Comment by aebruno** [comment]
Yeah see 5acdd11d941d4bba80d9e5f67de5779cc10e0c0b. The database schema changed and requires a rebuild. If you don't mind losing your message data you can run (where you installed whisperfish):

    $ rm ~/.local/share/harbour-whisperfish/db/*

Then restart whisperfish. This will only rebuild the message store (you won't have to re-register). Before the first release I will be implementing database migrations which will preserve message data in the case where the db schema changes. Sorry for the inconvenience.

**Comment by carepack** [comment]
perfect. up and running. thx
