### ISSUE TITLE
bug report appreciated for experimental feature? No contacts on desktop client

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#14]
Hi bruno,

should I open issues for linking devices? Really impressive the progress you've made!!! Thanks a lot!

No contacts are selectable. Only after a new message is arriving, I'm able to reply, but names are not beeing shown.

**Comment by aebruno** [comment]
Yes, feel free to open tickets. I have not tested this feature against the production servers yet.. only tested in a development environment. 

Were you able to link successfully? Contact numbers show up but not the names? Can you check to make sure your country code is set.

**Comment by carepack** [comment]
Hi @aebruno ,
I have succesfully linked my laptop with whisperfish. It needs more testing. Not showing contact names is one thing. On the other hand it seems that not every message is synchronized. At this point I can only confirm that for example messages posted to a group chat in whisperfish are not appearing on the desktop. Also vice versa. Posts into groups from desktop not appearing in whisperfish. Btw. is it intended to have the new icon only on whisperfish's cover page? App launcher icon should also be changed ;). I like it!
To investigate a little deeper into the desktop client it would be cool to have someone I can test with. Can't ask friends (they don't know what I'm talking about) and can't bother my group chats all the time.

So, yes the country code is definetely set. Contact numbers are shown but not the names. I can only reply to messages that I received on the desktop too. Start a completely new conversation is not possible because searching for contacts came up without any result.

**Comment by carepack** [comment]
ok. I try to document the behaviour.
I = me, F = friend, A = app, D = desktop. So it started with single chat. 
I, A send text -> not on desktop client
F, A send text -> received by me in A,D
I, D send text -> I replied from desktop. Is showing in D but not in A

group chats
I, A send text -> not shown in D
F, A send text -> received by me in A, D
I, D send text -> not shown in A 

So in the end, it looks to me that received messages from friends are correctly synced between desktop and app. Messages I sent, were only visible where I wrote them.

**Comment by aebruno** [comment]
> Btw. is it intended to have the new icon only on whisperfish's cover page? App launcher icon should also be changed ;). I like it!

For some reason the app icon gets cached and is not always updated after an rpm re-install. Perhaps a simple update of the icon would trigger a refresh?

    $ cp /usr/share/harbour-whisperfish/icons/86x86/harbour-whisperfish.png /usr/share/icons/hicolor/86x86/apps/harbour-whisperfish.png

If that doesn't work remove the app icon and re-install whisperfish:

    $ rm /usr/share/icons/hicolor/86x86/apps/harbour-whisperfish.png

**Comment by d9h02f** [comment]
I think icons in the launcher are only changed after a homescreen or device restart.

**Comment by carepack** [comment]
@d9h02f no. 
@aebruno thx. the update of the icon without deleting whisperfish worked.
