### ISSUE TITLE
visual bug - text is taken to a view where it shouldn't be

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#16]
Situation:
1. Be in a group chat
2.  The first entry is a picture like: http://imgur.com/9NBmo0Q
3. If you click now on the image to enter the picture view
4. You'll end up in with misplaced text: http://imgur.com/WXXAAv5

**Comment by aebruno** [comment]
Just fixed this one.. see 7a0bf4a32a01e501e2b969212336338861f44116

**Comment by carepack** [comment]
sorry, only looked out for modify date in code overview. haven't seen that commit. closed
