### ISSUE TITLE
visual enhancemant - overlaying dot on picture

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#17]
Like you can see in this screenshot: http://imgur.com/9NBmo0Q

the dot for turning back to message overview page lays over the picture. Guys like me are clicking on the image to view the picture. So it often happens that I hit the button instead of the picture. Maybe it would be better if the picture is a little bit lower.

greetz

**Comment by aebruno** [comment]
@carepack Fixing #20 should help with this. If the messages and chat input text box were anchored to the bottom of the page they wouldn't interfere with the back navigation.

**Comment by carepack** [comment]
ok. Will wait for #20 .

thx

**Comment by d9h02f** [comment]
Same thing happens when a picture is fullscreen, btw. Going by Gallery behaviour the dot should be behind the picture.
