### ISSUE TITLE
delete linked devices

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#19]
atm it's not possible to delete a device. maybe it's deleted but it's still listed.

**Comment by aebruno** [comment]
Did you link your device with Signal Desktop? How many devices are shown?

Note: currently whisperfish will always show itself as a device (the first device id=1). You can't delete this device. I'm debating on whether to show it at all.

**Comment by carepack** [comment]
so, then I'm going to close because it's not a bug. ID 1 is the device I meant. Thought it was created due a faulty connection durin pairing.
