### ISSUE TITLE
i486 and armv7hl target

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#2]
Hi, I've tried to compile the package. It's using as a default the i486 architecture. When I try to run mb2 -t SailfishOS-armv7hl build the process exit with error status bad rpm. Any ideas to run the armv7hl build?

Thx

**Comment by aebruno** [comment]
@carepack what version of go are you running? The arm builds seem to fail under go v1.5 but work fine for me under go v1.6.

**Comment by carepack** [comment]
@aebruno yes. right. it works with 1.6. the package is working well in the emulator. Are there any dependencies have to be installed on the phone?

**Comment by aebruno** [comment]
Are you using this patched version of [go-qml](https://github.com/aebruno/qml/tree/sailfish)?

**Comment by carepack** [comment]
i followed the readme steps. Installed via nekrondev buildscript and followed the manual steps.

**Comment by aebruno** [comment]
@carepack  Can you try this [branch](https://github.com/aebruno/qml/tree/whisperfish). For example, in MerSDK:

    $ cd ~/src/gopkg.in/
    $ rm -Rf qml.v1
    $ git clone https://github.com/aebruno/qml.git qml.v1
    $ git checkout whisperfish
    $ go install
    $ sb2 -O use-global-tmp -t SailfishOS-armv7hl ~/go/bin/linux_arm/go install

Then you can rebuild whisperfish using `mb2 -t SailfishOS-armv7hl build`. I tested the arm build and it's working for me on my jolla. Let me know if this works for you.

Thanks!

**Comment by carepack** [comment]
jep. thx ;) one step further. but sadly after enter my number for registration the app exits. Any idea? Thank you!

**Comment by aebruno** [comment]
@carepack OK think I fixed the bug. Can you try again? Will need to rebuild go-qml again:

     $ cd ~/src/gopkg.in/qml.v1
     $ git pull
     $ go install
     $ sb2 -O use-global-tmp -t SailfishOS-armv7hl ~/go/bin/linux_arm/go install

Then rebuild whisperfish. Let me know how it goes. Thanks for testing.

**Comment by carepack** [comment]
jep. app is up and running. I can start the registration process. But I don't receive a confirmation sms. np ;)

**Comment by aebruno** [comment]
perhaps it's the userAgent? Could try setting a different userAgent in `~/.config/harbour-whisperfish/config.yml`.

**Comment by aebruno** [comment]
@carepack you could also try setting verificationType to voice. It may be that sms verification is only supported for android and iOS. In `~/.config/harbour-whisperfish/config.yml` set:

    verificationType: voice

If this works for you I can make this the default.

**Comment by aebruno** [comment]
@carepack I can confirm voice verification works. I'll make this the default.

**Comment by carepack** [comment]
adding this 

> verificationType: voice

didn't help. no call received. So I pulled you're changes and builded again. Now I have to insert first a password. The text says now that I'll get a call. But I'm still not receiving a call.

**Comment by carepack** [comment]
yep, registration succesfull. my fault. number without + in front did the trick.

**Comment by aebruno** [comment]
Excellent. Glad to hear it worked for you. I'm going to go ahead and close this issue but feel free to open again or submit a new one if you have any troubles. Thanks again!
