### ISSUE TITLE
bug? - message syncing between desktop and app

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#22]
@aebruno 

ok. I try to document the behaviour for message syncing.
I = me, F = friend, A = app, D = desktop. So it started with single chat. 
I, A send text -> not on desktop client
F, A send text -> received by me in A,D
I, D send text -> I replied from desktop. Is showing in D but not in A

group chats
I, A send text -> not shown in D
F, A send text -> received by me in A, D
I, D send text -> not shown in A

So in the end, it looks to me that received messages from friends are correctly synced between desktop and app. Messages I sent, were only visible where I wrote them.

**Comment by carepack** [comment]
I reference this because it looks like a different problem but in both cases it looks that synchronizing is the problem #14

**Comment by d9h02f** [comment]
It's different for me. When I send a message from the desktop client, it shows up in Whisperfish, but when I send a message from Whisperfish, it shows up twice on the desktop, once with the sent tick and once with the sent+received double tick. I don't think they're actually sent twice, though.

Maybe worth mentioning is that I used the desktop client before with the Android client, so contacts and previous messages sent from the Android client were already there.

**Comment by carepack** [comment]
no

**Comment by aebruno** [comment]
> Maybe worth mentioning is that I used the desktop client before with the Android client

@d9h02f curious if you unlinked Signal-Desktop before you linked it with whisperfish?

**Comment by d9h02f** [comment]
Nope. Just registered on Whisperfish, opened up the desktop client, scanned the code and it worked immediately.

**Comment by carepack** [comment]
so I think it would be a good idea for @d9h02f and me to start from scratch with the desktop client. It's hard to get reliable info's when we're coming from two different szenarios.

**Comment by d9h02f** [comment]
I just realised that the duplicate messages appearing in the desktop client are only in group chats. Single conversations work just fine.

**Comment by bonanza123** [comment]
Maybe there is link between the multiple appearances of messages in group chats with that bug https://github.com/aebruno/whisperfish/issues/54 ? Is it possible that this bug is related to the Go back-end of whisperfish?
