### ISSUE TITLE
bug - overlapping text

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#23]
@aebruno 
But problem seems as coming back from time to time. iirc it happened in that moment a new message arrived and I had been in the overview page. seems that some messages have again two rows in the message overview.
See: https://veuwer.com/i/3uac

Seems related to #7

**Comment by carepack** [comment]
faced this now woth a one liner in the overview also.

**Comment by aebruno** [comment]
I refactored some of the qml code. This e3184da027d1cd0aeaf308c507bca9147e5e1e72 should hopefully help fix this issue.
