### ISSUE TITLE
Sending pictures is difficult and unclear

### ISSUE THREAD

**Issue by ghost** [aebruno/whisperfish#26]
Currently you have to hold the send button for a bit, release and then you get to choose the pictures you want to send. This should be done differently. I see two solutions:
- change the functionality of the button so that if there is no text entered yet, tapping it immediately brings you to the picture select screen (if/when audio/videos/etc are added, tapping the button could bring up a list with the available options, when would then lead to their separate file selection screens);
- use the pulley menu at the bottom to go to the picture select screen.

The first option seems like the best one, this is how it's done in the Android client as well, it would work well with what I mentioned in #24 and it has the benefit of not bloating the pulley menu with countless options.

**Comment by carepack** [comment]
how is the android version reacting when you write text and then insert a picture to the same message with text?

**Comment by d9h02f** [comment]
You have to select the picture first, otherwise it doesn't work and you can only send the text you typed.

**Comment by carepack** [comment]
I think the easiest and in design with sailfish would be swipe from right to left to enter the image picker

**Comment by d9h02f** [comment]
Could be, but this could also be a place, like in Messages, where the contact's information is shown. At least the Android client has a page for this as well. Maybe both could be in the same place.

**Comment by carepack** [comment]
i would add the contact info in the pulley menu at the bottom because it's not as many used as selecting media I think.

**Comment by mjtorn** [comment]
I was looking through these issues to see if there's something about attachments, because I didn't even realize Whisperfish supported them :D Most definitely "Attach media" in the bottom pulley would be clear and Sailfishy.

**Comment by aebruno** [comment]
Thanks for the feedback. I'll try to get this included in the next release.

**Comment by carepack** [comment]
i would refer to my post above -> swiping from rigt to left for entering image picker. Easier than the pulley menu entry to select (when there will be mor than one once).

**Comment by mjtorn** [comment]
AFAIU/IIRC you can attach other media types as well as pictures, right? By the protocol, not necessarily the current version of Whisperfish.

So what about attaching audio or video? That would need some kind of a submenu on the right-hand side, and to me it seems easier to pull the correct media type from below.

**Comment by d9h02f** [comment]
Then you end up with an endless pulley menu for all possible attachments. Ideally the pulley menu at the bottom shouldn't be there because it makes no sense when the keyboard is opened.

**Comment by mjtorn** [comment]
I don't have very strong opinions on this, but if/because other media types are supported by the protocol, it would be nice to have an intuitive UI to get to the attachment types and be able to handle them all :)

**Comment by d9h20f** [comment]
There is no longer a bottom pulley menu, so I'd definitely go for the first option now: if text has been entered already, long-pressing the send button lets you add attachments (which is how it currently works), but if no text has been entered yet, you only need to tap the send button to select attachments.
