### ISSUE TITLE
Picture selection improvements

### ISSUE THREAD

**Issue by d9h20f** [aebruno/whisperfish#27]
- [x] Currently the picture selection shows all the pictures on the device in order by folder and then chronologically, I believe it would be better to list all pictures in chronological order, otherwise it gets difficult trying to find the latest picture you took with the camera if you have lots of downloaded pictures.
- [x] I feel like it makes more sense to only show pictures from the Pictures and Downloads folders, otherwise you can end up with lots of irrelevant stuff. With a regular filepicker this wouldn't be too much trouble, but a grid quickly becomes a maze if it's filled with pictures you don't want to send.
- [x] Also see [this project](https://github.com/walokra/sailimgur) for what I think is a better picture selection screen.

**Comment by DanScharon** [comment]
the picture selection currently doesn't include the sd card (where I set the camera app to store photographs) which makes it even more of a hassle to share freshly taken pictures.

**Comment by aebruno** [comment]
@DanScharon See https://github.com/aebruno/whisperfish/issues/73#issuecomment-284922369

**Comment by DanScharon** [comment]
@aebruno thank you, it works!

**Comment by d9h20f** [comment]
This has been solved with the introduction of the ContentPicker.
