### ISSUE TITLE
detecting contacts

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#3]
detecting and recognizing contacts as signal contacts is only possible if the contact number is saved in international format +countrycodephonenumber
else whisperfish shows the message: user is not a signal user

**Comment by aebruno** [comment]
@carepack This commit should add better support for parsing local contacts. After installing the latest build you can go to the settings page and set your default country code. Then you can use the "Refresh Contacts" pull down menu to refresh your local contacts with signal.

**Comment by carepack** [comment]
I have to test a little bit more but it seems that not all contacts are detected. especially when something like "-" is in the number included.

**Comment by carepack** [comment]
moved to this: https://github.com/aebruno/whisperfish/issues/5
an closed. seems spaces related
