### ISSUE TITLE
Messages arriving in active conversation still generate notifications

### ISSUE THREAD

**Issue by ghost** [aebruno/whisperfish#33]
If a conversation is open and new messages arrive in it, it should be assumed that the user sees those messages arrive, so doesn't need to be informed about it again in the events screen.

**Comment by aebruno** [comment]
Can't reproduce this. If whisperfish is active and you're currently viewing the conversation page, a notification will be generated if a new message arrives from another contact.. i.e. not the current conversation you're viewing.

**Comment by d9h02f** [comment]
Maybe it's only in group chats, I don't use individual conversations that often so I'm not sure if I've seen it happen there.
