### ISSUE TITLE
Add ability to forward pictures to another chat

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#34]
hi @aebruno ,
iirc this functionality is implemented in the android client.
1. receive a message with a picture
2. press long on the picture to get options
3. now you can select to forward the picture to another chat

I thinks its very convinient instead selecting it from image picker. thx!

one question, in the settings is enabled to save attachments. but pictures I receive are not shown in the gallery app. Is there a special directory? application restart?

**Comment by aebruno** [comment]
> now you can select to forward the picture to another chat

Great idea. Will try to get this in next release. 

> one question, in the settings is enabled to save attachments. but pictures I receive are not shown in the gallery app. Is there a special directory? application restart?

This is related to #45
