### ISSUE TITLE
problem with ios signal client with new identity

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#37]
Hi @aebruno,
when I'm getting a new id after reinstall whisperfish android lets you accept the new keys of the contact and the message will be encrypted. On the iphone side people are only getting the message: a faulty message arrived. But nowhere is the option to accept keys or something else to encrypt. I don't know if this a ios thing but I reinstalled my android client multiple times and have never been affected by this problem iirc. Are you able to recheck this? Do you have a ios device?

**Comment by carepack** [comment]
Hi @aebruno ,
something  must have changed. Since upgrading to todays release all ios singalers are receivin' my messages again. Any idea?

**Comment by aebruno** [comment]
@carepack Not sure about this one. I have not had any issues sending messages to iOS users. Glad to hear it's fixed for you.
