### ISSUE TITLE
Messages received when offline get wrong timestamp

### ISSUE THREAD

**Issue by d9h02f** [aebruno/whisperfish#39]
Any messages received when Whisperfish was offline get a timestamp with the time the message was retrieved (so usually as soon as Whisperfish is back online), instead of the time the message was actually sent.

When receiving a lot of messages right after another Whisperfish sometimes hangs for a bit, and the messages also tend to get wrong timestamps then, even if they're only off by a few seconds the order between your own and your friends' messages can get messed up. I guess this has the same cause.

By the way, it would be great if you could upload an RPM of the latest iteration of Whisperfish, as I don't really have the resources to start compiling it myself.

**Comment by d9h02f** [comment]
Now, when opening Whisperfish to receive a bunch of messages from when it was offline, it crashes soon after entering the password! Should I post terminal output or do you know what is causing it?

**Comment by aebruno** [comment]
Sure feel free to post the terminal output and I'll take a look but would obviously recommend not posting any sensitive info.

**Comment by d9h02f** [comment]
Of course. Restarting my phone seems to have fixed it for now - all weather locations disappeared again, so it may be a problem with Sailfish itself and not with Whisperfish. I'll post the output next time it happens though.
