### ISSUE TITLE
timestamp of incoming messages always ahead

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#42]
Hi @aebruno ,
I have a problem with arriving chat messages. When my chat contact's local time is ahead of my time, the messages are always ahead in my chat history. Example
myMessage (send 12:19)
                               hisMessage(received 12:23 his local timestamp, but replied immediately)

when the chat is ongoing it looks something like this in the end:
1. myMessage (send 12:19)
3. myMessage (send 12:21 as reply to received message with timestamp at 12:23)
                               2. hisMessage(received 12:23)
                               4. hisMessage(received 12:25 as a reply to my message at 12:21)

So the arrived message is not getting my local timestamp And my message are alway behind the replies and not in shift until a longer break and my local time is then ahead the 12:23 timestamp.

And it happens with android and ios users. Here is the log http://cxg.de/_6fe9bb.htm

Version: release v0.3.0

And now more things going weird. I relinked my laptop and the behaviour changed now. I can see my messages always on both sides (doesn't matter wrote the message in whisperfish or desktop client). But arriving messages are only visible in whisperfish. And still no contact names. Also the timestamp problem from above is present. My message sent out of whisperfish has the timestamp now. On the desktop client where it appeared immediately shows 2 minutes ago. Desktop client log: http://cxg.de/_276d1d.htm

And it's getting more interesting: With one contact with the timestamp problem, I saw in the desktop client that I have to accept new keys of the user to encrypt. This is weird because in whisperfish the messages gettin' encrypted. After accepting, the messages of him are visible in both clients and the timestamp problem is gone. But with other contacts and the timestamp problem I don't see a message like this in the desktop client and so the problems still exists (wrong timestamp, arriving messages only in whisperfish)

**Comment by d9h02f** [comment]
I don't know if it's the exact same issue but one thing I've noticed with the timestamps is that Whisperfish checks the 'sent' timestamp of incoming messages, rather than the 'received' one, so if a contact has a different or a wrongly configured local time on their device, the messages show up in the wrong place in Whisperfish. Should be an easy fix.

**Comment by aebruno** [comment]
Yes, this is correct the sent timestamp is currently being used. Should be fixed in next release.
