### ISSUE TITLE
Support smilies

### ISSUE THREAD

**Issue by piratenpanda** [aebruno/whisperfish#44]
At the moment my wife can't see any smilies i send to her from my android signal. Is there a way to enable smilies yet?

**Comment by carepack** [comment]
You're missing a part that can interpret the character code. Problem in many apps so far. Try this one:
https://openrepos.net/content/penguin/emoji-keyboard

maybe it helps. At least for sending emoticons. You have to activate the keyboard in text input settings. After that you can switch the keyboard when typing a message with a long hold on the space key.

**Comment by d9h02f** [comment]
She's missing a font pack to display those characters. It's included in the emoji keyboard @carepack linked. You could also just add the font pack without installing the keyboard, but that's slightly more complicated and if you want to receive smilies you probably want to be able to send them as well.
