### ISSUE TITLE
"Copy to gallery" for received images not working

### ISSUE THREAD

**Issue by ghost** [aebruno/whisperfish#45]
"Copy to gallery" in the pulley menu for received images does not work for me on release 0.3.
It seems to do nothing, the images are not visible in the gallery afterwards.

**Comment by carepack** [comment]
if you have the option 'save attachements' enabled there's no need for. pictures should be there (gallery). sometines a tracker refresh help if they are not immediately visible

**Comment by ista** [comment]
"Save attachments" was activated from the very beginning. The pictures are still not in the gallery after a complete phone restart.
Deactivating and reactivating "Save attachments" has not helped either.

**Comment by carepack** [comment]
two things i observed
1. in sailfish utilities refresh media database
2. look out carefully for the picture. sometimes its not in chronolical order
3. tried to select the image in a new message from gallery? only to see if its visible there

**Comment by ista** [comment]
1. Have done this, no help
2. The pictures are not there. For comparison, the ones saved from a MMS message are.
3. They are not visible in the WhisperFish image selector either

**Comment by carepack** [comment]
ok, then its not longer working. youre right!

**Comment by aebruno** [comment]
@ista This is not currently implemented. You could try adding the directory where attachments are stored to tracker. See [here](https://together.jolla.com/question/5935/how-to-blacklist-directories-from-being-indexed-by-tracker/?answer=56730#post-id-56730). Something like this perhaps? (note this has not been tested so don't run this command without testing first):

    $ gsettings set org.freedesktop.Tracker.Miner.Files index-recursive-directories "['&DESKTOP', '&DOCUMENTS', '&DOWNLOAD', '&MUSIC', '&PICTURES', '&VIDEOS', '/home/nemo/.local/share/harbour-whisperfish/storage/attachments']"

The long term plan was to eventually encrypt the attachments on disk. Then the "Copy to Gallery" menu item would be necessary to decrypt the attachment for viewing in Gallery. But for now it does nothing

**Comment by carepack** [comment]
command is working. thid.mornimg I saw a patch on openrepos. It has a graphical interface to configute the tracket dirs. If gui is prefered

**Comment by mjtorn** [comment]
@carepack where's the patch for this? Would be interesting to take a look :)

Otherwise +1 for a functioning Copy to Gallery feature, it's somewhat annoying to do this the long way around...

**Comment by mjtorn** [comment]
@aebruno would it be possible to have a setting like "Show Whisperfish images in gallery" at least for as long as they're not encrypted? So if that's set to true, it would check on startup if the attachments directory is in that index path and add it if not.

**Comment by aebruno** [comment]
Yes, this sounds like a good idea. I would likely make a subdirectory under ~/Pictures/whisperfish and store the attachments in there. Not sure if that's against harbour policies but seems like a reasonable approach. This would eliminate the need for a "Copy to Gallery" feature as they would already be included.
