### ISSUE TITLE
Group management

### ISSUE THREAD

**Issue by yorambh** [aebruno/whisperfish#46]
while basic group chat seems to work (you can send messages to group and receive from it) although, with not-so-intuitive UI, I can't find any group management actions (add to group, remove from group, etc..).
are there any plans to support this ?

**Comment by aebruno** [comment]
Group support is quite lacking and not very well tested. I personally don't use group messaging at all so it's been lower on the priority list.

**Comment by MoritzJT** [comment]
I've installed the prebuilt v0.3.0 and registered. Is this version supposed to pull my existing groups yet? Because they do not show in the UI but work with the Desktop Client once connected...

**Comment by marxistvegan** [comment]
@aebruno Wondering if we can bring this up to a higher priority? Certainly something that I would like to see added and I am willing to help test it out as well

**Comment by aebruno** [comment]
@marxistvegan What group functionality are you most interested in? add/remove from group?

**Comment by marxistvegan** [comment]
@aebruno yeah the ability to add someone to a group would be great! Apparently removing someone else from a group is not part of signal, at least from the brief info I read on that, but certainly removing oneself. 
Only if it is not hard to be able to set the image for the group would be a nice added feature

**Comment by marxistvegan** [comment]
@aebruno So leaving groups is also an important feature too... The use of groups at seems to be growing as of late with a lot of activists and organizers. Any thoughts on how or what we can do to help, that being me not being a coder but a tester ;)

**Comment by aebruno** [comment]
I'll bump this up on the todo list. WIll try and include it in the next release.

**Comment by marxistvegan** [comment]
just checking in, any update on creating and leaving groups?

**Comment by marxistvegan** [comment]
Going to bump this again... is there a patch to be tested? 
A number of groups I work with are using groups more exclusively

**Comment by aebruno** [comment]
@marxistvegan Sorry for the delay. Nothing to release yet but hopefully soon.

**Comment by marxistvegan** [comment]
Though i have note full tested the new group management, the lack of scrolling or search to select members to join a group makes it challenging.
