### ISSUE TITLE
app starting without internet connection

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#49]
all my contacts are synced via carddav. when I have no internet connection no names are visible in whisperfish. only numbers. close the app, establish internet connection and open app again bring the names back

**Comment by aebruno** [comment]
You can also try "Settings -> Refresh Contacts" instead of restarting the app.

**Comment by carepack** [comment]
the contacts and messages are appearing after the connection is established. not seeing the messages happens not all the time. contact names happens the the whole time. so the question is, why need whisperfish an active connection to show a conversation (sometimes) or either contact names?

**Comment by aebruno** [comment]
Currently, the app does not store any of your contact names and looks them up in the local nemo contact database. On startup or when you select "Refresh Contacts" it sends your contact list to Signal to determine which of them are also Signal users. It will only show the names of active Signal users. This should be an easy fix to show contact names for existing conversations. I would also like to add an option to disable sending the contact list to Signal if the user prefers.

**Comment by sfbg** [comment]
In version 0.4.0 when the option "Share contacts" is turned off, only the numbers are shown and never the names from the address book.

**Comment by aebruno** [comment]
Should be able to enable "Share contacts" and then "Refresh Contacts". Does that work for you?

**Comment by sfbg** [comment]
Well, the idea is to not enable Share contacts and still replace the numbers with the entries from the local phone book.

**Comment by aebruno** [comment]
OK I see.. yes didn't think of that case. Should be able to add this in.
