### ISSUE TITLE
contact names missing

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#5]
in the messages overview only phone numbers are visible. no names at all.

**Comment by carepack** [comment]
it seems that not all contact names are missing in message overview. the difference:
contact name shown: number is a complete string. "-" inlcuded
contact name not shown: number string contains spaces

**Comment by aebruno** [comment]
@carepack I can't seem to reproduce this one. I tested a few contacts with spaces in the numbers and they show up for me. Can you provide an example contact info?

**Comment by carepack** [comment]
the structure of the number looks exactly like this:

+49 123 12345678

**Comment by carepack** [comment]
ok. time to close. after rebuild and updated name is shown now. will close the issue and reopen it when needed
