### ISSUE TITLE
New messages are not received when whisperfish is locked

### ISSUE THREAD

**Issue by bonanza123** [aebruno/whisperfish#53]
I made some experiments and noticed that, e.g. after a (re)start of the phone, new messages are not received or no notification is issued when whisperfish is started but not yet unlocked. Is it possible to change this behavior?

**Comment by aebruno** [comment]
No unfortunately the app has to be open and unlocked in order to send/receive messages.

**Comment by bonanza123** [comment]
@aebruno Thanks for your response. I assume I can then close this issue.
