### ISSUE TITLE
Use Whisperfish without password

### ISSUE THREAD

**Issue by d9h02f** [aebruno/whisperfish#55]
I don't think an application password is all that useful so I would like to get rid of it, and I noticed there is a line in .config/harbour-whisperfish/config.yml called "unencryptedStorage: false". Setting this to true seems to remove the need for a password, but it gets rid of everything in the process as you have to reregister and all previous messages are gone. Is it possible to get rid of the password without the need to register again?

**Comment by aebruno** [comment]
The app forces the user to set a password at first install. I'd like to change this to be optional. Once the password is set, all files except for attachments, are encrypted using this password. To get rid of the password you'd have to first decrypt all the files then restart Whisperfish with "unencryptedStorage: false". I've never tried removing the password once it's set so there may be other setups involved. It's certainly possible the app could have an option for this and would be a great feature to add.

**Comment by d9h02f** [comment]
How would I go about decrypting the files?
