### ISSUE TITLE
No new messages until changed identity is verified

### ISSUE THREAD

**Issue by bonanza123** [aebruno/whisperfish#56]
Here is what I noticed twice:
1.) Chat partner has signal client X installed
2.) I chat with this partner 
3.) Chat partner changes client and thereby also his identity changes
4.) Chat partner sends me additional messages (e.g. one in a personal and one in a group chat) for which I don't get a notification and which I can't see in whiserpfish
5.) I go to the personal chat with him and send him a message which triggers an info where I shall verify his new identity
6.) With slight delay I now receive all the messages he/she sent under 4.)

In order to always receive these notifications, it may be a good idea to always watch out for identity changes and directly notify the user. The messages which were received with the new and not yet verified identity could be mark with the red triangle so something like that.

**Comment by aebruno** [comment]
Thanks for the detailed info. I'm not sure this is possible as any messages sent by your chat partner would not be received until you accept their new key. The only way to do this is to send them a message. It's at that time when you can reset and accept their new identity key. If I'm not mistaken this is similar to how the android app currently works?

**Comment by bonanza123** [comment]
@aebruno  Thanks for your reply! Frankly, I can't fully remember how the official android app handles this. But I have situation in my mind where the app just shows something like "Partner has changes the identity" with a red triangle. By long click on this message there was an option to verify the new identity. Then, the actual message was displayed instead of the note above.
