### ISSUE TITLE
High resource footprint

### ISSUE THREAD

**Issue by sfbg** [aebruno/whisperfish#59]
The app, when just idly running, takes at least 25% of the RAM on my Jolla 1. Here is a screenshot from Lighthouse:

![screenshot_20161222_001](https://cloud.githubusercontent.com/assets/24361624/21469016/5a088630-ca34-11e6-8d2a-8ff739bef031.png)

What is more, when I leave Whisperfish running, the battery is drained at least twice as fast as normal. 

Any chance of improvement on this front?

**Comment by aebruno** [comment]
What version are you running? How many messages do you have (Settings -> Statistics)?

**Comment by sfbg** [comment]
I am using v 0.3.0
There are 1800 messages in 8 sessions.

I do not think this issue depends on the number of sessions or messages, the memory footprint was like this from the beginning when I started using WhsperFish, and has not increased since.

**Comment by sfbg** [comment]
Unfortunately, no improvement with v 0.4. Still >25% RAM usage at all times.
Am I the only one with this problem?

**Comment by aebruno** [comment]
I typically see ~6-10% RAM.

**Comment by marxistvegan** [comment]
Mine is low too not 25% running on JollaC

**Comment by sfbg** [comment]
Interesting. I'm on a Jolla 1. The fact that most of my chats are in Cyrillic couldn't play a role, right? It's just UTF-8 I suppose.

**Comment by sfbg** [comment]
Right after startup v 4.1.0 still consumes 27% memory, but after a while it goes to 11%. It seems to be an improvement from the previous versions. 10% is still sizable, though.

**Comment by sfbg** [comment]
I guess it was something specific on my Jolla 1.
The migrated profile on my Xperia loads and uses 2% memory.
