### ISSUE TITLE
add better notifications

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#6]
Hi,

say a word and I'll stop spamming ;)

When new messages are arriving and been shown in jolla's notification overview, the expected behaviour when clicking the message is to enter the whisperfish app. But it only deletes the message from jollas message center and stays there.

Also it would be a cool idea to show messages of one contact as one row in the notification center of jolla. atm you'll get a very long list of messages from one contact. of course: cosmetic

**Comment by d9h02f** [comment]
The long list is the way all other applications do it as well (unless I misunderstand), why change it?

**Comment by carepack** [comment]
because the list is getting to long :-) it makes no sense imho. sms ok. but messenger?
iirc other messenger we're goin different ways also. Don't know if it was hangish or whatsup.

**Comment by d9h02f** [comment]
But you can only see five notifications of one application at a time anyway.

**Comment by aebruno** [comment]
> say a word and I'll stop spamming ;)

Feel free to keep submitting issues! I really appreciate the feedback.

I agree the notifications need some work. At minimum it should open whisperfish to the correct conversation when clicking on the notification.  As @d9h02f  there's a limit to how many notifications are shown per app (on my jolla it shows 3 messages and then "Show more..").  Looking into this more and should have some updates soon.

**Comment by aebruno** [comment]
@carepack Clicking on a notification should now take you to the conversation.

**Comment by aebruno** [comment]
Closing this out. Feel free to reopen if somethings missing.

**Comment by d9h02f** [comment]
Is it supposed to be the case that now every new notification replaces the old one (from the same conversation/contact)? The point of the events screen is to be able to see everything that's going on without having to open each application individually, but it gets frustrating when I only see the last message which usually tends to be my contact correcting a typo. You also don't get an extra notification if a previous notification is updated, so if you miss the one short vibration of the first notification, you'll never know you've received 20 other messages, or in fact anything at all. If you don't want your phone to vibrate all the time when you're busy with something, you could just turn off your WiFi and mobile data. The events screen lets you remove individual notifications so you can get rid of the unimportant ones and keep those you might end up forgetting about if you opened them.

I really think it makes more sense here to adhere to the way Jolla does it. The Messages application is used for a lot more IM services than it is for SMS.

**Comment by carepack** [comment]
@aebruno I think @d9h02f and me are not able to reopen issues. We have to create new ones.

**Comment by aebruno** [comment]
> I think @d9h02f and me are not able to reopen issues. We have to create new ones.

Think this is a limitation of Github?

**Comment by aebruno** [comment]
@d9h02f I was thinking of making this an options in the settings. It's easy enough to do either way and can see both sides.

**Comment by d9h02f** [comment]
I don't think making it an option would be right because it just doesn't make sense. On Android you have one notification that gets every new notification appended to it, and it keeps notifying on every changes. This is exactly what Sailfish does, only on Sailfish the big notification is split up in all of its parts. Last I checked, this is how iOS does it as well. I've never seen anything just replace a message notification with a more recent message to save space in the list of notifications, because it goes against all logic.
