### ISSUE TITLE
Encourage development to continue

### ISSUE THREAD

**Issue by marxistvegan** [aebruno/whisperfish#61]
Hey @aebruno I know that whispersystems has indicated they may cut off libresignal. As they do not have a client for Sailfish and have said they do not have the resources to develop for it I feel it leaves a window to continue the work. I would like to encourage it as I think now there are more people interested in signal. Just was to share this as I am not sure where else to express outside of a ticket.

Thanks for the great work!

**Comment by bonanza123** [comment]
Please note that there is work ongoing in bringing websocket support in the official andorid app, please see https://github.com/WhisperSystems/Signal-Android/pull/5962

**Comment by aebruno** [comment]
Thanks for the feedback. I'm still actively developing and working on refactoring/cleaning up the code. I plan on releasing a new version soon. Is there a feature/bug in particular that you would like to see fixed the most?

**Comment by carepack** [comment]
Some kindo of donation possible to support youre work? The most annoying thing is that whisperfish is often entering deepsleep (oom?) after a while and isn't receiving any messages. When you tab it on the homescreen it's coming up like starting the app and you have to enter the password. Is there anything you could do about? thx bruno

**Comment by marxistvegan** [comment]
@aebruno great to hear. I created a discussion in whispersystems forum on the idea of supporting clients for unsupported mobile OSs here https://whispersystems.discoursehosting.net/t/resources-to-support-jolla-devices/712 if it is of any help. 

Glad to hear and look forward to seeing the update. :)

**Comment by carepack** [comment]
@marxistvegan
in whisperforum you can add the beauty of sfos apps and gesture based navigations as argument. I red somewhere that whispersystems is planning to ban 3rd parity apps, but I'm not sure. In that case it would be a good idea to whisper :-) about non official clients. 

wish a nice day

**Comment by marxistvegan** [comment]
@carepack yeah that is why i did not mention specifically which client. I will update it to include the interface and gestures. thanks :)

**Comment by carepack** [comment]
@marxistvegan
np :-)

scrolling to the top sidebar would be also nice

**Comment by marxistvegan** [comment]
Really happy to see the updates coming in...looking forward to seeing the release package!

**Comment by tvicol** [comment]
Thanks for your work, aebruno !

**Comment by paolomi** [comment]
great app! Please continue! There are only 2-3 things to do:  Encrypted attachments (most important), Archiving conversations (important), Multi-Device support (I don't care of it). :-)

**Comment by bonanza123** [comment]
Maybe just a stupid question, but which part of "Multi-Device support" is not yet working? I'm using it since a while a didn't notice a problem...

**Comment by aebruno** [comment]
@bonanza123 Glad to hear it's working for you. Multi-Device support is still a work in progress. Hasn't been thoroughly tested with groups and there are still a few lingering bugs. I do not currently use multiple devices so haven't gotten around to working on this feature.

**Comment by marxistvegan** [comment]
hey all i would really like to bring this back, with the SailfishX and new devices in Latin America, I feel there is a good chance people will be interested. I am wondering if there is any way to use in this case both the official Signal APK and Whisperfish on the same device with the same fingerprint, in part for testing and in part for dealing with missing features...i.e. groups. Thoughts?

**Comment by aebruno** [comment]
@marxistvegan Unfortunately, there is no way to use both the official Signal APK and Whisperfish on the same device with the same fingerprint. You could however use them with different numbers. I'm hoping to release a new version soon with a few minor updates which should include better support for group chat.

**Comment by marxistvegan** [comment]
@aebruno Thanks for the feedback. As for the update... I am deeply looking forward to it :) Any timeline or rough timeline?
