### ISSUE TITLE
Voice/Video calls

### ISSUE THREAD

**Issue by mjtorn** [aebruno/whisperfish#70]
Hi!

Still loving the work you're doing, yet I have to ask, are the non-message features on your roadmap?

This caught my eye earlier: [Video calls for Signal now in public beta ](https://whispersystems.org/blog/signal-video-calls-beta/) because sometimes it would be nice to call (and receive calls!) over Signal :)

Cheers!

**Comment by petrica-celrau** [comment]
@aebruno, please consider voice/video calls. I have terrible signal at home and wifi is my only way of calling. Actually the absence of voice/video calls in Sailfish OS is the only thing that keeps me from using it full time.

**Comment by oleid** [comment]
So webrtc is used and they're doing the key exchange via signal's infrastructure. Did anybody find more documentation on that matter?

Now that gstreamer has webrtc support[1], I was wondering if one could re-use that to bring video support to whisperfish.

[1] https://www.phoronix.com/scan.php?page=news_item&px=GStreamer-WebRTC-Lands
