### ISSUE TITLE
Possible bug: changing networks

### ISSUE THREAD

**Issue by mjtorn** [aebruno/whisperfish#72]
Hi!

Sometimes I don't get messages until I go to `Settings` and `Reconnect`. Nowadays I try to remember doing it when I go from WLAN to 3G to WLAN, eg. on my way home.

Would it be possible for Whisperfish to recognize it lost the WLAN connection and reconnect, or conversely notice that 3G was replaced by WLAN and reconnect?

Thanks!

**Comment by aebruno** [comment]
Yes, this should be fixed in c1518724c3b78da3968b9f2557c4f6363303fc9a

Will do a new release soon.

**Comment by mjtorn** [comment]
How's it looking with the release? I guess I could package this for myself but I'd be surprised if the connection issues weren't affecting a lot of people ;)

Thanks!

**Comment by bonanza123** [comment]
a new build would be nice :-)

**Comment by aebruno** [comment]
Just released v0.4.1. Let me know if this helps with network reconnects.  Should auto-reconnect better now but I still occasionally have to force re-connect when switching from 3g to wlan.

**Comment by mjtorn** [comment]
After the upgrade I got an error about Signal client, and when I restarted to pay more attention to the error, everything started up nice. SailfishOS 2.0.5.6 community port on the Fairphone2.

Will definitely let you know if there are further connection problems :)

Thanks a lot!

**Comment by sfbg** [comment]
My experience concerning reconnecting has improved tremendously after the 4.1.0 update. It is virtually always online now. From my view this issue can be closed.

**Comment by holvimjt** [comment]
I think I've had like one problem where the connection went bad for no apparent reason, which made me thing a reconnect cover button could be a nice addition to the connection status. But if it's very uncommon, it might not be worth opening an issue about.

Thanks for the good work @aebruno!

**Comment by mjtorn** [comment]
I think I've had like one problem where the connection went bad for no apparent reason, which made me thing a reconnect cover button could be a nice addition to the connection status. But if it's very uncommon, it might not be worth opening an issue about.

Thanks for the good work @aebruno!

**Comment by aebruno** [comment]
@sfbg @mjtorn Thanks for reporting back.
