### ISSUE TITLE
MicroSD image or file source selection

### ISSUE THREAD

**Issue by marxistvegan** [aebruno/whisperfish#73]
When I try to attach an image I am only presented with the default home/nemo/Pictures and not able to change the source selection. This is on the JollaC device. Is there a missing option for this that I am not aware or is this a bug?

**Comment by aebruno** [comment]
Yes, this path is currently hard coded at the moment. The plan is to make this a config option similar to `attachment_dir`

**Comment by marxistvegan** [comment]
oh that would be great!

**Comment by aebruno** [comment]
v0.4.2 includes a new config option `search_paths` which you can set to the paths you'd like searched for images files when sending attachments. You will have to manually edit his file: 
  `/home/nemo/.config/harbour-whisperfish/harbour-whisperfish.conf` 

and set the `search_paths`. For example:

```ini
[General]
search_paths=/home/nemo/Pictures,/home/nemo/Documents,/home/nemo/Music
```

**Comment by marxistvegan** [comment]
Worked well, I put the /media/sdcard/<name>/Pictures first so that it puts the more recent photo at the top.
