### ISSUE TITLE
panic runtime error on websocket connect [Resolved by upgrade to v0.4.3

### ISSUE THREAD

**Issue by marxistvegan** [aebruno/whisperfish#78]
Having some connection issues and was able to copy this when running from command line. Seems something with the websocket is having a runtime error. This reproducible on every start I am not able to maintain a connection.

>  All queried in 1185 ms
> [D] unknown:0 - Online queried in 1219 ms
> [D] onTriggered:156 - Page status: 2
> [W] unknown:194 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:194: TypeError: Cannot read property 'backIndicatorDown' of null
> [W] unknown:189 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:189: TypeError: Cannot read property 'backIndicatorDown' of null
> [W] unknown:247 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:247: TypeError: Cannot read property 'forwardIndicatorDown' of nul
> l
> [W] unknown:242 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:242: TypeError: Cannot read property 'forwardIndicatorDown' of nul
> l
> [W] unknown:51 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/PageEdgeTransition.qml:51: TypeError: Cannot read property of null
> [W] unknown:50 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/PageEdgeTransition.qml:50: TypeError: Cannot read property of null
> [W] unknown:49 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/PageEdgeTransition.qml:49: TypeError: Cannot read property of null
> INFO[2017/04/10 22:21:11] Attempting to open encrypted datastore
> INFO[2017/04/10 22:21:11] Database dir: /home/nemo/.local/share/harbour-whisperfish/db
> INFO[2017/04/10 22:21:11] Connecting to encrypted data store
> DEBU[2017/04/10 22:21:12] Get local contacts handler
> DEBU[2017/04/10 22:21:12] PUT /v1/directory/tokens 200
> 
> DEBU[2017/04/10 22:21:13] GET /v1/devices/ 200
> 
> DEBU[2017/04/10 22:21:16] Starting client websocket listener
> DEBU[2017/04/10 22:21:16] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/
> DEBU[2017/04/10 22:21:16] Websocket Connected successfully
> panic: runtime error: slice bounds out of range
> 
> goroutine 37 [running]:
> github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure.handleReceivedMessage(0x0, 0x0, 0x0, 0x753418, 0x93f90c20)
> /home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/textsecure.go:462 +0xa2c
> github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure.StartListening(0x0, 0x0)
> /home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/websocket.go:180 +0x36c
> github.com/aebruno/whisperfish/worker.(*ClientWorker).start(0x93f3e2a0)
> /home/src1/projects/go/src/github.com/aebruno/whisperfish/worker/client.go:84 +0xb0
> created by github.com/aebruno/whisperfish/worker.(*ClientWorker).init.func1
> /home/src1/projects/go/src/github.com/aebruno/whisperfish/worker/client.go:61 +0x80

**Comment by bonanza123** [comment]
Same here (I guess): https://pastebin.com/Q2CFcWfE

**Comment by DanScharon** [comment]
same here, looks indeed like a server side change

**Comment by fletchers** [comment]
since there's no private messaging unfortunately:
@marxistvegan how did you create this log? I'm new to sailfish and all, and I'd love to be able to share more useful information like this.
cheers,
fletchers

**Comment by bonanza123** [comment]
@fletchers using linux's `journalctl`

**Comment by aebruno** [comment]
> how did you create this log? I'm new to sailfish and all, and I'd love to be able to share more useful information like this.

@fletchers If you start whisperfish with the `-d` option it will write debugging output to a file `/tmp/whisperfish-app.log`:
```
   $ harbour-whisperfish -d
```

Note: there may be sensitive info (contact numbers etc.) so you may want to sanitize before posting any output.

**Comment by tvicol** [comment]
Here is my output:

[nemo@Sailfish ~]$ harbour-whisperfish -d
[D] unknown:0 - Using Wayland-EGL
[W] unknown:38 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/Util.js:38: TypeError: Cannot read property 'parent' of null
[D] unknown:0 - Starting favorites query at 362 ms
[W] unknown:194 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:194: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:189 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:189: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:247 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:247: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:242 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:242: TypeError: Cannot read property 'forwardIndicatorDown' of null
[D] unknown:0 - Starting metadata query at 637 ms
[D] unknown:0 - Favorites queried in 660 ms
[D] unknown:0 - Starting online  query at 764 ms
[D] unknown:0 - Online queried in 783 ms
[D] unknown:0 - All queried in 898 ms
[D] onTriggered:156 - Page status: 2
[W] unknown:194 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:194: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:189 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:189: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:247 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:247: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:242 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:242: TypeError: Cannot read property 'forwardIndicatorDown' of null

**Comment by aebruno** [comment]
@tvicol thanks..but the useful bits are in the log file `/tmp/whisperfish-app.log`

**Comment by tvicol** [comment]
@aebruno 
Thanks ! here it is:

[nemo@Sailfish ~]$ cat /tmp/whisperfish-app.log
INFO[0000] Starting Whisperfish version 0.4.3-0-g2ac3fb7 
INFO[0000] No translations found for system locale. Using default  locale=C
INFO[0000] Setting up whisperfish directories           
INFO[0000] Config dir: /home/nemo/.config/harbour-whisperfish 
INFO[0000] Data dir: /home/nemo/.local/share/harbour-whisperfish 
INFO[0000] Attachments dir: /home/nemo/.local/share/harbour-whisperfish/storage/attachments 
INFO[0000] Checking search path: /home/nemo/Pictures    
INFO[0000] Attachment search paths: [/home/nemo/Pictures] 
INFO[0000] Parsing Signal config                        
INFO[0000] Storage dir: /home/nemo/.local/share/harbour-whisperfish/storage 
INFO[0000] Server:                                      
INFO[0000] Identity key found. Already registered       
INFO[0002] Setting up whisperfish client                
INFO[2017/04/11 16:43:00] Prompting for storage password               
INFO[2017/04/11 16:43:19] Attempting to open encrypted datastore       
INFO[2017/04/11 16:43:19] Database dir: /home/nemo/.local/share/harbour-whisperfish/db 
INFO[2017/04/11 16:43:19] Connecting to encrypted data store           
DEBU[2017/04/11 16:43:19] Get local contacts handler                   
DEBU[2017/04/11 16:43:20] PUT /v1/directory/tokens 401
                
ERRO[2017/04/11 16:43:20] Failed to fetch signal contacts               error=status code 401

DEBU[2017/04/11 16:43:21] GET /v1/devices/ 401
                        
DEBU[2017/04/11 16:43:24] Starting client websocket listener           
DEBU[2017/04/11 16:43:24] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:24] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:27] Starting client websocket listener           
DEBU[2017/04/11 16:43:27] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:28] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:31] Starting client websocket listener           
DEBU[2017/04/11 16:43:31] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:31] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:34] Starting client websocket listener           
DEBU[2017/04/11 16:43:34] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:35] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:38] Starting client websocket listener           
DEBU[2017/04/11 16:43:38] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:39] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:42] Starting client websocket listener           
DEBU[2017/04/11 16:43:42] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:42] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:45] Starting client websocket listener           
DEBU[2017/04/11 16:43:45] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:46] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:49] Starting client websocket listener           
DEBU[2017/04/11 16:43:49] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:49] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:52] Starting client websocket listener           
DEBU[2017/04/11 16:43:52] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:53] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:43:56] Starting client websocket listener           
DEBU[2017/04/11 16:43:56] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:43:57] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:00] Starting client websocket listener           
DEBU[2017/04/11 16:44:00] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:00] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:03] Starting client websocket listener           
DEBU[2017/04/11 16:44:03] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:04] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:07] Starting client websocket listener           
DEBU[2017/04/11 16:44:07] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:07] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:10] Starting client websocket listener           
DEBU[2017/04/11 16:44:10] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:11] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:14] Starting client websocket listener           
DEBU[2017/04/11 16:44:14] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:15] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:18] Starting client websocket listener           
DEBU[2017/04/11 16:44:18] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:18] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:21] Starting client websocket listener           
DEBU[2017/04/11 16:44:21] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:22] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:25] Starting client websocket listener           
DEBU[2017/04/11 16:44:25] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:26] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:29] Starting client websocket listener           
DEBU[2017/04/11 16:44:29] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:30] Error processing Websocket event from Signal  error=websocket: bad handshake
DEBU[2017/04/11 16:44:33] Starting client websocket listener           
DEBU[2017/04/11 16:44:33] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ERRO[2017/04/11 16:44:34] Error processing Websocket event from Signal  error=websocket: bad handshake
[nemo@Sailfish ~]$

**Comment by oleid** [comment]
Yesterday, I installed Whisperfish and it worked 'till this morning:

All I get is:

[34mINFO[0m[0000] Starting Whisperfish version 0.4.2-0-gcd02c33 
[34mINFO[0m[0000] Successfully loaded system locale             [34mlocale[0m=en_GB
[34mINFO[0m[0000] Setting up whisperfish directories           
[34mINFO[0m[0000] Config dir: /home/nemo/.config/harbour-whisperfish 
[34mINFO[0m[0000] Data dir: /home/nemo/.local/share/harbour-whisperfish 
[34mINFO[0m[0000] Attachments dir: /home/nemo/.local/share/harbour-whisperfish/storage/attachments 
[34mINFO[0m[0000] Checking search path: /home/nemo/Pictures    
[34mINFO[0m[0000] Attachment search paths: [/home/nemo/Pictures] 
[34mINFO[0m[0000] Parsing Signal config                        
[34mINFO[0m[0000] Storage dir: /home/nemo/.local/share/harbour-whisperfish/storage 
[34mINFO[0m[0000] Server: https://textsecure-service.whispersystems.org:443 
[34mINFO[0m[0000] Identity key found. Already registered       
[34mINFO[0m[0001] Setting up whisperfish client                
[34mINFO[0m[2017/04/11 15:53:37] Prompting for storage password               
[34mINFO[0m[2017/04/11 15:53:49] Attempting to open encrypted datastore       
[34mINFO[0m[2017/04/11 15:53:49] Database dir: /home/nemo/.local/share/harbour-whisperfish/db 
[34mINFO[0m[2017/04/11 15:53:49] Connecting to encrypted data store           
[37mDEBU[0m[2017/04/11 15:53:49] Get local contacts handler                   
[37mDEBU[0m[2017/04/11 15:53:53] PUT /v1/directory/tokens 200
                
[37mDEBU[0m[2017/04/11 15:53:53] GET /v1/devices/ 200
                        
[37mDEBU[0m[2017/04/11 15:53:56] Starting client websocket listener           
[37mDEBU[0m[2017/04/11 15:53:56] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
[37mDEBU[0m[2017/04/11 15:53:57] Websocket Connected successfully             
[34mINFO[0m[2017/04/11 15:53:57] Incoming WhisperMessage invalid message: no valid sessions. Ignoring.
 
time="2017-04-11T16:00:29+02:00" level=info msg="Starting Whisperfish version 0.4.2-0-gcd02c33" 
time="2017-04-11T16:00:29+02:00" level=info msg="Successfully loaded system locale" locale="en_GB" 
time="2017-04-11T16:00:29+02:00" level=info msg="Setting up whisperfish directories" 
time="2017-04-11T16:00:29+02:00" level=info msg="Config dir: /home/nemo/.config/harbour-whisperfish" 
time="2017-04-11T16:00:29+02:00" level=info msg="Data dir: /home/nemo/.local/share/harbour-whisperfish" 
time="2017-04-11T16:00:29+02:00" level=info msg="Attachments dir: /home/nemo/.local/share/harbour-whisperfish/storage/attachments" 
time="2017-04-11T16:00:29+02:00" level=info msg="Checking search path: /home/nemo/Pictures" 
time="2017-04-11T16:00:29+02:00" level=info msg="Attachment search paths: [/home/nemo/Pictures]" 
time="2017-04-11T16:00:29+02:00" level=info msg="Parsing Signal config" 
time="2017-04-11T16:00:29+02:00" level=info msg="Storage dir: /home/nemo/.local/share/harbour-whisperfish/storage" 
time="2017-04-11T16:00:29+02:00" level=info msg="Server: https://textsecure-service.whispersystems.org:443" 
time="2017-04-11T16:00:29+02:00" level=info msg="Identity key found. Already registered" 
time="2017-04-11T16:00:30+02:00" level=info msg="Setting up whisperfish client" 
time="2017/04/11 16:00:30" level=info msg="Prompting for storage password" 
time="2017/04/11 16:00:39" level=info msg="Attempting to open encrypted datastore" 
time="2017/04/11 16:00:39" level=info msg="Database dir: /home/nemo/.local/share/harbour-whisperfish/db" 
time="2017/04/11 16:00:39" level=info msg="Connecting to encrypted data store" 
time="2017/04/11 16:00:39" level=debug msg="Get local contacts handler" 
time="2017/04/11 16:00:41" level=debug msg="PUT /v1/directory/tokens 200\n" 
time="2017/04/11 16:00:41" level=debug msg="GET /v1/devices/ 200\n" 
time="2017/04/11 16:00:44" level=debug msg="Starting client websocket listener" 
time="2017/04/11 16:00:44" level=debug msg="Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/" 
time="2017/04/11 16:00:45" level=debug msg="Websocket Connected successfully" 
time="2017/04/11 16:00:45" level=info msg="Incoming WhisperMessage invalid message: no valid sessions. Ignoring.\n" 
 
And on stdout/-err:

[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL 
[W] Silica::ThemePrivate::ThemePrivate:432 - Defaulting to webview scaling factor of 1.0 
[W] DeclarativeWindow::DeclarativeWindow:94 - No default allowed orientations defined. Check your device configuration! 
[W] execute:1715 - "Query failed: no such function: icu_load_collation Unable to execute statement
SELECT icu_load_collation('en_GB', 'localeCollation')" 
[W] configureDatabase:1854 - "Failed to configure collation for locale en_GB:  " 
[W] unknown:38 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/Util.js:38: TypeError: Cannot read property 'parent' of null
[D] SeasideCache::startRequest:1610 - Starting favorites query at 200 ms 
[W] unknown:189 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:189: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:194 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:194: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:247 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:247: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:242 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:242: TypeError: Cannot read property 'forwardIndicatorDown' of null
[D] SeasideCache::startRequest:1655 - Starting metadata query at 510 ms 
[D] SeasideCache::applyPendingContactUpdates:2457 - Favorites queried in 514 ms 
[D] SeasideCache::startRequest:1665 - Starting online  query at 595 ms 
[D] SeasideCache::applyPendingContactUpdates:2461 - All queried in 641 ms 
[D] SeasideCache::requestStateChanged:2834 - Online queried in 648 ms 
[D] onTriggered:156 - Page status: 2
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:68 - Initializing plugin 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:93 - Reading setting for Press : 20 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:94 - Reading setting for Release : 18 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:95 - Reading setting for PressWeak : 10 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:96 - Reading setting for ReleaseWeak : 7 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:97 - Reading setting for PressStrong : 30 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:98 - Reading setting for ReleaseStrong : 25 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:99 - Reading setting for DragStart : 5 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:100 - Reading setting for DragDropInZone : 15 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:101 - Reading setting for DragDropOutOfZone : 0 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:102 - Reading setting for DragCrossBoundary : 10 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:103 - Reading setting for Appear : 0 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:104 - Reading setting for Disappear : 0 
[D] QFeedbackDroidVibrator::QFeedbackDroidVibrator:105 - Reading setting for Move : 0 
[D] QFeedbackDroidVibrator::deviceProfileSettingsChanged:133 - Profile settings changed: enabled: true level: 1 
[W] unknown:189 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:189: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:194 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:194: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:247 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:247: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:242 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:242: TypeError: Cannot read property 'forwardIndicatorDown' of null
panic: runtime error: slice bounds out of range

goroutine 24 [running]:
github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure.handleReceivedMessage(0x0, 0x0, 0x0, 0x753418, 0xd4827d60)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/textsecure.go:462 +0xa2c
github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure.StartListening(0x0, 0x0)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/websocket.go:180 +0x36c
github.com/aebruno/whisperfish/worker.(*ClientWorker).start(0xd47303f0)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/worker/client.go:84 +0xb0
created by github.com/aebruno/whisperfish/worker.(*ClientWorker).init.func1
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/worker/client.go:61 +0x80

**Comment by aebruno** [comment]
@oleid Try upgrading to v0.4.3

**Comment by aebruno** [comment]
@tvicol You appear to be having a similar issue as #77. See this comment on how to re-register https://github.com/aebruno/whisperfish/issues/77#issuecomment-288986752

**Comment by oleid** [comment]
@aebruno : Thanks, that helps!

**Comment by marxistvegan** [comment]
@aebruno Thanks that did resolve the problem...I will move to close awesome response time :)

**Comment by tvicol** [comment]
@aebruno Re-registering solved the problem. Thanks !

**Comment by bonanza123** [comment]
Same issue for me on 0.4.4. Please see http://termbin.com/67uj

**Comment by aebruno** [comment]
> Please see http://termbin.com/67uj

Thanks for the log. This looks like it may be a different bug. Looking into it. 

> Do I really need to delete all files as mentioned here #77 (comment) ? This also deletes current conversations right?

If you want to re-register (which I'm not sure will solve your problem) and preserve your conversations, then you should only need to delete `/home/nemo/.config/harbour-whisperfish/config.yaml` and `/home/nemo/.local/share/harbour-whisperfish/storage`

**Comment by bonanza123** [comment]
@aebruno sorry for being (potentially) annoying, but did you already have the time to look into that issues? Do I indeed need to re-register?

**Comment by aebruno** [comment]
@bonanza123 No worries at all and sorry for the delay. I hope to have a new build you can try in the next few days.

**Comment by bonanza123** [comment]
@aebruno Thanks so much! Btw, downgrading to 0.4.3 solved that issue.

**Comment by aebruno** [comment]
@bonanza123 Hoping v0.4.5 will solve your issue. I'm not able to reproduce but from the debug log you sent it looks as though you were still receiving legacy messages which were removed in v0.4.4. Added a check to prevent panic when receiving those messages however please note they will not show up in whisperfish and are silently ignored.

**Comment by sfbg** [comment]
Can confirm that updating to 0.4.5 solves the crash at startup when connected with this trace:

```
panic: runtime error: index out of range

goroutine 20 [running]:
github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/axolotl.LoadWhisperMessage(0x0, 0x0, 0x0, 0x7605b8, 0xd440ef00, 0x0)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/axolotl/messages.go:42 +0x388
github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure.handleReceivedMessage(0xd46e2900, 0x11b, 0x11b, 0x7607d8, 0xd43cda20)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/textsecure.go:475 +0x350
github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure.StartListening(0x0, 0x0)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/vendor/github.com/aebruno/textsecure/websocket.go:183 +0x6a4
github.com/aebruno/whisperfish/worker.(*ClientWorker).start(0xd40b20c0)
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/worker/client.go:95 +0xc0
created by github.com/aebruno/whisperfish/worker.(*ClientWorker).init.func1
	/home/src1/projects/go/src/github.com/aebruno/whisperfish/worker/client.go:68 +0x80
```

**Comment by sfbg** [comment]
By the way, what exactly are "legacy messages"?

**Comment by sfbg** [comment]
By the way, what exactly are "legacy messages". A friend still uses the LibreSignal release for SailfishOS and it seems to send such messages. He sees them as successfully received by me.
