### ISSUE TITLE
new message contact suggestion 

### ISSUE THREAD

**Issue by carepack** [aebruno/whisperfish#8]
When I start a new message, I enter the contact row and start typing. Normally suggestions should be shown of contacts which then are easily chooseable. Atm you have to click first the "+" button to enter contacts list and select them there.

**Comment by carepack** [comment]
idea because I don't how youre goin to handle this
1. suggestion based on only signal users then.everything will be fine.

2 if suggestion is based on all contacts of addressbook then a message shoul be shown that contact is a non signal user (like it does atm.) but maybe with a button the leads to the sms app of jolla to send an invitation. would be more like the native android client.

**Comment by aebruno** [comment]
> 1. suggestion based on only signal users then.everything will be fine.
This would be my preference but not sure how (or if it's possible) to add a custom filter to the PeopleModel. For now the error message will be displayed if the contact is not in Signal.

>  maybe with a button that leads to the sms app of jolla to send an invitation.
This would be nice also and will tag this as a feature.

**Comment by carepack** [comment]
amazing. thx a lot!

**Comment by aebruno** [comment]
Closing and moved SMS invitation to new issue #12
