### ISSUE TITLE
whisperfish no longer connect with 2.1.0.11 Iijoki

### ISSUE THREAD

**Issue by tvicol** [aebruno/whisperfish#80]
Just updated my phone and "Websocket status" is flapping between Connected/Diconnected.
It may be related to Qt6 websockets used in latest 2.1.0.11 Iijoki ?

**Comment by bonanza123** [comment]
dupe of https://github.com/aebruno/whisperfish/issues/78 ?

**Comment by tvicol** [comment]
Thanks bonanza123 ! Seems to be related.

**Comment by bonanza123** [comment]
Note also there is already a new version of whisperfish (0.4.3): https://github.com/aebruno/whisperfish/releases

**Comment by tvicol** [comment]
Yes. No joy with 0.4.3 as well.

**Comment by aebruno** [comment]
@tvicol v0.4.3 is working for me, however I'm still on  2.0.5.6. Whisperfish does not use Qt websockets so shouldn't be an issue. Did you restart whisperfish after upgrading?

**Comment by tvicol** [comment]
@aebruno   Thanks for response ! It was working fine on 2.0.5.6. Issue appeared after upgrade to 2.1.0.11 Iijoki.

**Comment by rrunner64** [comment]
v0.4.3 is working for me with 2.1.0.11. Issue and upgrade may be a coincidence, as I upgraded to 2.1.0.11 several days ago and had no issues with v0.4.2 until this morning.

**Comment by sfbg** [comment]
v0.4.3 is fine on 2.1.0.11 for me too. The issue was not due to the Sailfish version.

**Comment by Nokius** [comment]
I'm on 2.1.0.x for long time it was working tile 10/11.04 fine. after the update to v0.4.3 *and* a reregistration all is working again for me

**Comment by tvicol** [comment]
All is fine after re-registration. thanks for support !
