### ISSUE TITLE
Audio attachment cannot be opened

### ISSUE THREAD

**Issue by holvimjt** [aebruno/whisperfish#81]
Hi!

I just got what I assume to be a voice message from a friend of mine.

Hitting the musical-note icon gives me an empty QML page, except for "From ..." and the timestamp.

Is this a known issue?

Thanks!

**Comment by aebruno** [comment]
Yes, currently you can only view video and picture attachments. There's no good way to get the file info on attachments either (I hope to fix this soon). You could try and find the attachment on the command line:
```
$ find /home/nemo/.local/share/harbour-whisperfish/storage/attachments/ -printf "%T+\t%p\n" | sort
``` 

Should list out all your attachments sorted by date. Then you could either use the file browser app to play the audio attachment or scp it somewhere you can play it.

**Comment by holvimjt** [comment]
I found one file without an extension. This is the first time I receive a voice message and I got it covered by texting back. Didn't put the effort into copying the file over, but I think that's the one.

Is this something you can fix? What's the biggest obstacle?
