### ISSUE TITLE
How to migrate/backup whisperfish registration and messages

### ISSUE THREAD

**Issue by bonanza123** [aebruno/whisperfish#82]
My JollaC battery has died and I installed a port of SFOS on an older android device. Is there way to migrate whisperfish (registration and messages) to the new phone? Which files do I have to copy?

**Comment by d9h02f** [comment]
There are two folders you should copy:

/home/nemo/.local/share/harbour-whisperfish
/home/nemo/.config/harbour-whisperfish

This should make Whisperfish work as it did before. Report back on how it went!

**Comment by aebruno** [comment]
Copy the folders @d9h20f mentioned above. Also, if you configured a different attachment folder you'll need to copy that as well. You can check this file: 

  `/home/nemo/.config/harbour-whisperfish/harbour-whisperfish.conf`

For a setting called `attachment_dir`.
