### ISSUE TITLE
Settings problem with attachment directory

### ISSUE THREAD

**Issue by mjtorn** [aebruno/whisperfish#83]
Hi!

#45 introduced automatic saving of gallery images. I don't often need to forward or care about images (or videos for that matter) that I receive, but now I'd easy access to one.

I found the image under `~/.local/share/harbour-whisperfish/storage/attachments/` and I'd like to configure it to store under `~/Pictures/Whisperfish/`.

Unfortunately, I can't find where to do this. Quickly greping around the code, it looks like settings.go just check whether or not `attachment_dir` is set, but I can't seem to find it.

My version is v0.4.3-0-g2ac3fb7 which should be the latest one.

Have I gone blind?

Thanks!

**Comment by aebruno** [comment]
Edit the file config file located here:

   `/home/nemo/.config/harbour-whisperfish/harbour-whisperfish.conf`

The setting is `attachment_dir`. Set this to  `/home/nemo/Pictures/Whisperfish`

To preserve your existing attachments you can optionally move to the new location:

   `mv ~/.local/share/harbour-whisperfish/storage/attachments ~/Pictures/Whisperfish/`

Then restart.

**Comment by mjtorn** [comment]
Ok, nice; I was looking for a UI :)

Thanks for the help!
