### ISSUE TITLE
Sending attachment image to Signal client fails

### ISSUE THREAD

**Issue by mjtorn** [aebruno/whisperfish#85]
Hi!

Tried sending an image to someone using Signal, who gets this error
![signal-whisperfish-fail](https://user-images.githubusercontent.com/78427/32593007-d8a42a76-c52e-11e7-86dc-f9b43f79578f.jpg)

I haven't received any images from a Signal user since this error appeared nor have I tried sending one to another Whisperfish user.

Has the protocol changed so that Whisperfish needs to adapt?

This feels like a pretty severe bug, any possibility of fixing it?

Thanks!

**Comment by aebruno** [comment]
I can reproduce. Looks like the api may have changed. We'll try and get a fix out soon.

**Comment by aebruno** [comment]
@mjtorn This should hopefully be fixed. Tested best I could. Let me know if you're still having issues.
