### ISSUE TITLE
Can Signal-Desktop be repurposed with a Qt interface?

### ISSUE THREAD

**Issue by physkets** [aebruno/whisperfish#87]
https://github.com/WhisperSystems/Signal-Desktop

**Comment by d9h20f** [comment]
Signal Desktop is an Electron application, meaning it's essentially an entire browser that only loads the Signal webpage. It's pretty terrible, takes up huge amounts of storage space and RAM, and it isn't standalone so you would need Whisperfish or Signal Android to use it anyway.
