### ISSUE TITLE
Webocket cant connect since today

### ISSUE THREAD

**Issue by monkeyisland1992** [aebruno/whisperfish#90]
Hi there since today whisperfish cant connect to websockets.
The app connect and disconnet every second. No sending any Messages.
Rebooting the phone does not help

**Comment by Nokius** [comment]
duplicate see #89

**Comment by Nokius** [comment]
for me both whisperfish and desktop are working again

**Comment by aebruno** [comment]
@monkeyisland1992 let us know if you're still having an issue. Closing for now.
