### ISSUE TITLE
SailfishX 2.1.4.14 (maybe) isssue

### ISSUE THREAD

**Issue by objectifnul** [aebruno/whisperfish#91]
After having reflashed my Xperia X, I couldn't re-register it. Device verification code never received (several attempts).

**Comment by aebruno** [comment]
@objectifnul Could be related to #89 and you happened to try and re-register when signal servers were down? As a last resort, you could try deleting `/home/nemo/.config/harbour-whisperfish/` and `/home/nemo/.local/share/harbour-whisperfish` and restarting? Beware this will delete **_all_** your message data and config settings etc. This should re-registering the device and allow you to start fresh. 

If you're still having issues it could be a bug. Haven't tested on 2.1.4.x yet.

**Comment by objectifnul** [comment]
Did so. No success. Looks like my (Belgian) phone number couldn't be reached by Signal server.
Will try again from an other country when possible.
Is there any whisperfish-specific log file to be checked?

**Comment by aebruno** [comment]
> Is there any whisperfish-specific log file to be checked?

If you start whisperfish with the `-d` option it will write debugging output to a file `/tmp/whisperfish-app.log`:
```
   $ harbour-whisperfish -d
```

Note: there may be sensitive info (contact numbers etc.) so you will want to sanitize the output before posting anywhere public.

**Comment by objectifnul** [comment]
See attached 'whisperfish_debug.zip'

[whisperfish_debug.zip](https://github.com/aebruno/whisperfish/files/1781891/whisperfish_debug.zip)

**Comment by Nokius** [comment]
@objectifnul do you block over sea calls? iirc signal called me  via a +1 number

**Comment by objectifnul** [comment]
No, I don't. However, in the past, my provider (proximus.be) had some issues with incoming international calls.

**Comment by aebruno** [comment]
Took a quick look at the logs and it appears whisperfish is working. Did not see any errors that would indicate the request for verification code failed.

**Comment by objectifnul** [comment]
OK, thanks. So I will investigate elsewhere. Do my logs indicate that Signal server received my request? If yes, there is probably a problem with my mobile operator.

I close the issue.

**Comment by Nokius** [comment]
Did you found a solution ?

**Comment by objectifnul** [comment]
No. Some other users have a similar issue. I'm afraid there is no solution unless Mr. Marlinspikes'policy changes for more openness.

**Comment by rubdos** [comment]
[I posted a workaround on TJC](https://together.jolla.com/question/181042/whisperfish-device-verification-code/?answer=183784#post-id-183784). I'm using a text message here, instead of a voice call. You might want to use that too in the program itself, @aebruno.

**Comment by idnovic** [comment]
I had an issue too.

But for me the problem was the registration pin. In the official app you can password protect the registration. And whisperfish does not support this feature.

**Comment by mschilli87** [comment]
>But for me the problem was the registration pin. In the official app you can password protect the registration. And whisperfish does not support this feature.

see https://github.com/aebruno/whisperfish/issues/116 for the corresponding issue
