### ISSUE TITLE
[request] picture resizing to safe bandwidth

### ISSUE THREAD

**Issue by Nokius** [aebruno/whisperfish#92]
Since I have the Xperia I'm not able to share pictures when I reached my fare to use quota. Which makes it impossible to share any taken picture. Is there a possibility to add a compression when sharing pictures?

**Comment by aebruno** [comment]
Hi @Nokius, can you describe your use case here a bit more? You want to be able share compressed pictures to save on bandwidth usage charges? jpeg images are already compressed so not sure how much smaller we can make them.

**Comment by Nokius** [comment]
Yes I would like to use less bandwidth.

an random selected picture with my Xx
~~~~
1.2M	Pictures/Camera/20180314_165247.jpg
~~~~
resizing the picture would be the solution

random picture received via Telegram (128K)
~~~~
Size: 960x1280
~~~~

my example picture 
~~~~
Size: 5312x2988
~~~~

**Comment by aebruno** [comment]
Great, thanks. Yes this should be possible. Would likely make this another config setting "image_size" and allow user to set their preferred image size when sending picture attachments.

**Comment by Nokius** [comment]
yeap that sounds great :)

**Comment by Nokius** [comment]
Thanks that was quick!

**Comment by aebruno** [comment]
It's definitely not perfect and hasn't been thoroughly tested but should hopefully do the trick for you. Did a quick test on 1.2M image taken on my Jolla one and it only sends 157K over the wire. As noted, the orientation of the resized image may differ from the original. Also should mention that this does not change the original image on disk at all and re-scales the image attachment in memory before sending.

**Comment by Nokius** [comment]
it sounds good to me I will let you know about the image quality if someone will complain on the other end :D

**Comment by Nokius** [comment]
I tested the feature but the Picture wasn't send :(

How could I debug it?

**Comment by Nokius** [comment]
after looking into it bit closer.

The resizing is happening so it can be only an issue with the bandwidth or how files are send :-/

**Comment by aebruno** [comment]
Can you check the logs? I adjusted some http timeouts and wondering if you're getting any tls handshake timeouts. If so, try re-sending the message right after it fails and seeing if it goes through.

**Comment by Nokius** [comment]
I tried to resend it two times. I need to get a new SIM card my last one expired yesterday morning.

**Comment by Nokius** [comment]
it works better for me, lately How can I see the logs?

**Comment by aebruno** [comment]
See this comment for how to log: https://github.com/aebruno/whisperfish/issues/78#issuecomment-293264856
