### ISSUE TITLE
Groups not shown after re-registering

### ISSUE THREAD

**Issue by bonanza123** [aebruno/whisperfish#94]
Because I had to re-install SFOS, I also had to re-register whisperfish and, thus, lost my conversations.
New non-group chats are showing up as usual after new messages. However, new messages in groups I'm in (and where I receive messages from via synced desktop apps) are not shown and I also do not receive notifications from these groups. 

Edit:
Oopps, have just seen there are were some commits concerning group handling etc. I hope this gets fixed in this version too (I'm on v0.4.5)

**Comment by aebruno** [comment]
@bonanza123 Sorry to hear you're having troubles. Just to confirm, are you seeing issues with groups you were a member of before re-installing SFOS? So new groups you joined after the re-install are working fine but previous groups are not?

**Comment by tuokiv** [comment]
I'm having a same issue. Messages are not coming into groups being member before installing Whisperfish. Re-adding to group by other member solves problem. Also new groups made with Whisperfish are working.

**Comment by marxistvegan** [comment]
Oh version .5 I have the issue where the groups I was in will show on the linked desktop app but not on the phone itself in whisperfish.

**Comment by dragonchaser** [comment]
I am having the same issue on 0.5.1

**Comment by muppeth** [comment]
is there a way to leave the group from desktop client or otherwise. i could then be re-invited.

**Comment by bonanza123** [comment]
@muppeth maybe the group owner can remove you and add you?

**Comment by marxistvegan** [comment]
> @muppeth maybe the group owner can remove you and add you?

That is unfortunately not a feature in Signal groups.

**Comment by muppeth** [comment]
Seems like changing the name of the group is sufficient to get back in.

On Tuesday, 6 November 2018, Stephen wrote:
> > @muppeth maybe the group owner can remove you and add you?
> 
> That is unfortunately not a feature in Signal groups.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/aebruno/whisperfish/issues/94#issuecomment-43628194

-- 
Sent from my Sailfish device

**Comment by marxistvegan** [comment]
> Seems like changing the name of the group is sufficient to get back in.
> […](#)
> On Tuesday, 6 November 2018, Stephen wrote: > @muppeth maybe the group owner can remove you and add you? That is unfortunately not a feature in Signal groups. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#94 (comment)](https://github.com/aebruno/whisperfish/issues/94#issuecomment-43628194)
> -- Sent from my Sailfish device

So the creator of the group or someone in the group would have to do that correct?

**Comment by muppeth** [comment]
yes. thats correct. The moment they do, you will see the group again 
and can interact with it.
